on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Tag of the commit you want to deploy'
        required: true
        type: string

jobs:
  trigger-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ArgoCD repo
        uses: actions/checkout@v2
        with:
          repository: MaYohann/argocd-gs-rennes3d-apps
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: ./argocd
      - name: Update key
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag =  = strenv(TAG)' ./argocd/argocd-gs-rennes3d-apps/apps/dev/vcmap-demo/values.yaml
        env:
          TAG: ${{ inputs.tag }}
      - name: Push to ArgoCD repo
        run: |
          cd ./argocd
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "[Rennes3D] Deploy ${TAG}"
          git push
        env:
          TAG: ${{ inputs.tag }}
